#!/usr/bin/python3
def raise_exception():
    y = 5
    x = 'Hello'
    return y + x
